### ISSUE TITLE
make imfile support symlinks in monitored directories (requires some polling)

### ISSUE THREAD

**Issue by Dieken** [rsyslog/rsyslog#2229]
I have this file layout with wildcard file "/path/to/xx/yy/zz/*.log":

```
/path/to/xx/yy/zz/a-short-file-name.log ->  /another/path/a-very-long-file-name.log
```

After I delete `/another/path/a-very-long-file-name.log` and recreate it,  imfile in inotify mode doesn't automatically reopen abc.log.  If I delete `a-short-file-name.log` and sym-link again,  imfile continues to read `a-very-long-file-name.log` but it will miss some lines because I use imfile with parameter "freshStartTail=on".

I work around this issue by link `/path/to/xx/yy/zz` to `/another/path`,  imfile works correctly but I have to accept the very-long-file-name.

This issue also affects cronolog(https://linux.die.net/man/1/cronolog) when cronolog keeps a symlink "error.log" to latest "error.log.YYYYmmddHH",  but this is not severe since cronolog quickly recreates the symlink. 

In my actual scenario,  Docker rotates `/var/lib/docker/containers/A-LONG-CONTAINER-ID/A-LONG-CONTAINER-ID.log` to `/var/lib/docker/containers/A-LONG-CONTAINER-ID/A-LONG-CONTAINER-ID.log.1` and recreates `/var/lib/docker/containers/A-LONG-CONTAINER-ID/A-LONG-CONTAINER-ID.log`.  The symlink `/path/to/xx/yy/zz/a-short-file-name.log` is maintained by my own cron job , the symlink won't be recreated from time to time because the target file almost always exists.

platform: Ubuntu 14.04 & 16.06 with ppa:adicson/v8-stable.

**Comment by Dieken** [comment]
Just noticed I changed the path name in code block but didn't change  path name in description, sorry,  fixed it.

**Comment by rgerhards** [comment]
so I guess this is solved

**Comment by Dieken** [comment]
@rgerhards  No, it's not solved, I mean I updated the issue description and fixed some wrong wording.

**Comment by rgerhards** [comment]
@alorbach can you please have a look?

**Comment by alorbach** [comment]
Can you create a debug log which before and after the logrotate?

**Comment by Dieken** [comment]
@alborbach,  if the symlink isn't recreated,  Rsyslog with inotify can't detect the target file is recreated, so Rsyslog doesn't output anything during the log rotation.

**Comment by rgerhards** [comment]
> if the symlink isn't recreated, Rsyslog with inotify can't detect the target file is recreated, so Rsyslog doesn't output anything during the log rotation.

OK, than it is more a doc issue. If it can't be done decently with inotify, it is outside the feature set of imfile.

@deoren what do you think?

**Comment by deoren** [comment]
> @rgerhards: OK, than it is more a doc issue. If it can't be done decently with inotify, it is outside the feature set of imfile.
> 
> @deoren what do you think?

I'm not sure I fully understand the scenario, so I'm afraid my feedback may not be worth much. If the desired behavior is truly outside of the feature set offered by imfile, then I believe that we should update the docs to note the lack of support for this scenario. Perhaps an entry in the "Caveats/Known Bugs" section if this turns out to be the case.

As I understand it, the imfile module supports reading in multiple modes, two of them being polling and inotify. Does polling give better support for picking up changes to symbolic links vs inotify?

**Comment by rgerhards** [comment]
polling mode offers limited functionality, because it does not periodically poll large parts of the file system for globbing. Inotify instead monitors the file system (efficiently) for changes. We get a notification from the kernel when something in the monitored location changes, so then we pick up these changes. If I understood @Dieken correctly, symlink changes will not be reported. So this would again require polling and so is outside of the scope of imfile. 

I don't say this can be changed, but then it needs to. And I don't think it would be a good idea to change it, as again we would get overhead for globbing large parts of the file system on a continous basis.

**Comment by Dieken** [comment]
Maybe Rsyslog can periodically stat() the symlink to check whether its inode had changed,  or Rsyslog can inotify-watch(dirname(realpath(symlink))) to check whethet the target file is recreated.

Actually my workaound is very like the second way, I use a symlink to directory instead of file, so Rsyslog can watch the directory. The bad side is I have to accept the target file name.

I’m fine to document this issue as known limitation, thank you the same for your support!

**Comment by rgerhards** [comment]
Let's document this and change the issue here to an enhancement request.

**Comment by jvymazal** [comment]
@rgerhards  how is the status of the refactoring task please? I would be interested in helping with this, however if you are close to changing the code in some significant way I would rather wait a bit and work on top of those changes.
Thanks

**Comment by rgerhards** [comment]
@jvymazal The core work is done, PR is https://github.com/rsyslog/rsyslog/pull/2533

I'll hopefully merge today. It shows a couple of CI errors, but if I see correctly they are all due to actual testbench issues which I have worked on. Will do a rebase to master now and lets see how it progresses. Any contributions are of course very welcome. Please also have a look at https://github.com/rsyslog/rsyslog/projects/4 - I plan to include at least the state file refactoring with the next release.

**Comment by linsomniac** [comment]
Also note that if you do not use freshStartTail and you do use inotify mode, it will re-process the log file everytime cronolog restarts writing to the sym or hard link.  I believe this is because inotify will tell rsyslog about the brief unlink and recreate.

We have been tracking this because we were seeing weird spikes after releases and I tracked it down to the logs being loaded again from scratch when cronolog restarted.

I also note that in the imfile documentation it says " In theory, there should never be a reason to enable “polling” mode and later versions will most probably remove it.".  This makes me reluctant to switch to polling mode and I've instead switched away from using cronolog.  However, I wish I didn't have to.

**Comment by linsomniac** [comment]
It would be nice if rsyslog sees a new file that has the same inode as the old file, and is the same size or larger than the old file, it didn't restart processing it from the beginning.

**Comment by rgerhards** [comment]
If the file is not deleted in the interim, the state file has all Infos and imfile does exactly what you say.

**Comment by rgerhards** [comment]
closed via https://github.com/rsyslog/rsyslog/pull/2749
