### ISSUE TITLE
imfile: statefile must follow when IN_MOVE_SELF

### ISSUE THREAD

**Issue by kortemik** [rsyslog/rsyslog#2484]
### Expected behavior
When a file is moved inside watched directory (IN_MOVE_SELF), from a path that matches glob pattern of the input to a path that matches the same input glob pattern, the statefile should be moved accordingly and file should not be re-read when rsyslog is restarted.
When a file is moved to a path that does not match a glob pattern, statefile should be deleted.
This behaviour should be perhaps configurable.
### Actual behavior
File is handled as a new file, therefore rotated files are read twice when rsyslog is restarted. 
### Steps to reproduce the behavior
configure imrelp to monitor a pattern such as /opt/files/*.log
start rsyslog
create a file with content named /opt/files/move_me.log
move file /opt/files/move_me.log to /opt/files/move_me.2018-02-16.log
restart rsyslog
### Environment
- rsyslog version: 8.27
- platform: Centos 7.4
- for configuration questions/issues, include rsyslog.conf:

*Note: rsyslog documentation is available here*:
  [pre-release](http://www.rsyslog.com/doc/master/),
  [current stable release](http://www.rsyslog.com/doc/v8-stable/)

**Comment by alorbach** [comment]
I believe this is already fixed in 8.28, see this commit: 
https://github.com/rsyslog/rsyslog/commit/f19ead255126745c6ea7cb1949e49f22cf940a1a#diff-b563a9e8d7f28e380e7fd4dc4467d3e8

When I file is moved inside the watch, the statefile is handeled and moved as well

**Comment by kortemik** [comment]
some inconsistencies still exist with wildcards and paths but we will check after refactoring of imfile
