### ISSUE TITLE
RSyslog 8.9 crashes with Elasticsearch/MySQL Output

### ISSUE THREAD

**Issue by joschi99** [rsyslog/rsyslog#298]
RSyslog 8.9.0 crashes on startup. The last messages in the logfile are:
Apr  8 21:30:37 osiris2 rsyslogd-2359: action 'action 5' resumed (module 'omelasticsearch') [v8.9.0 try http://www.rsyslog.com/e/2359 ]
Apr  8 21:30:37 osiris2 rsyslogd-2359: action 'action 5' resumed (module 'omelasticsearch') [v8.9.0 try http://www.rsyslog.com/e/2359 ]
Apr  8 21:30:37 osiris2 rsyslogd-2359: action 'action 1' resumed (module 'ommysql.so') [v8.9.0 try http://www.rsyslog.com/e/2359 ]
Apr  8 21:30:37 osiris2 rsyslogd-2359: action 'action 1' resumed (module 'ommysql.so') [v8.9.0 try http://www.rsyslog.com/e/2359 ]

Restarting RSyslog deamon manually everthing works correct.

We use RSyslog to send all logs to a local Elasticsearch 1.5.0 Index and also to a local MariaDB 5.5. We have this error since we upgraded to RSyslog 8.9.0 and Elasticsearch 1.5.0. Both upgrades where done in the same time trough yum (rpm). OS is SL 6.6.

**Comment by joschi99** [comment]
Downgrading to RSyslog 8.8.0.ad1 everything works fine with Elasticsearch 1.5.0. The last messages in the logfile are still:
Apr  8 21:49:27 osiris2 rsyslogd-2359: action 'action 5' resumed (module 'omelasticsearch') [v8.8.0.ad1 try http://www.rsyslog.com/e/2359 ]
Apr  8 21:49:27 osiris2 rsyslogd-2359: action 'action 5' resumed (module 'omelasticsearch') [v8.8.0.ad1 try http://www.rsyslog.com/e/2359 ]
Apr  8 21:50:01 osiris2 rsyslogd-2359: action 'action 1' resumed (module 'ommysql.so') [v8.8.0.ad1 try http://www.rsyslog.com/e/2359 ]
Apr  8 21:50:01 osiris2 rsyslogd-2359: action 'action 1' resumed (module 'ommysql.so') [v8.8.0.ad1 try http://www.rsyslog.com/e/2359 ]

The difference is that 8.8.0 will not crash on server startup.

**Comment by stephanbuys** [comment]
Can't reproduce this with Elasticsearch 1.5.1, Rsyslog 8.9.0 on Ubuntu 14.04.2, just thought it might be useful to mention.

**Comment by stephanbuys** [comment]
Actually scratch that, managed to reproduce exact problem described here on another Ubuntu 14.04.2 machine.

**Comment by rgerhards** [comment]
Do you use the errorfile capability? Or even better: can you post your rsyslog.conf?

There was recently a patch for omelasticsearch ( https://github.com/rsyslog/rsyslog/pull/246 ) and even though it looked fine, the problem may be related to it. For that reason, it would also be great if you could downgrade to 8.8.0 and check if the problem persists.

**Comment by stephanbuys** [comment]
Is there a way to downgrade using the ppa? (on Ubuntu), I'm willing to test but a bit stumped

**Comment by davidelang** [comment]
apt doesn't give you a nice way to downgrade  (as a general rule, downgrades aren't tested, only upgrades)

what you can do is either download the relevant .deb packages and install them manually via dpkg (and disable auto-updates), or you can pin the version via apt and then uninstall/reinstall to have it get the specific version.

**Comment by stephanbuys** [comment]
Also willing to enable errorfile, but in the meantime here is my rsyslog.conf 
https://gist.github.com/stephanbuys/4042be18ea71d202443a

Let me know if there are any other debug options I can run.

**Comment by stephanbuys** [comment]
@davidelang manual install is fine, is there a URL to the 8.8.0 series of debs? (for amd64) I've tried i386 but couldn't install...

**Comment by davidelang** [comment]
The PPA is at https://launchpad.net/~adiscon/+archive/ubuntu/v8-stable

clicking on "view package details" gets you to 
https://launchpad.net/~adiscon/+archive/ubuntu/v8-stable/+packages

clicking on "### successful" under completed builds takes you to 
https://launchpad.net/~adiscon/+archive/ubuntu/v8-stable/+builds?build_state=built

looking at the list of builds, you can find "amd64 build of rsyslog 
8.8.0.ad1-0adiscon4trusty1 in ubuntu trusty RELEASE" clickong on it takes you to 
https://launchpad.net/~adiscon/+archive/ubuntu/v8-stable/+build/7066881 which 
lists all the .deb packages

there's probably an easier way to do this. I know what's needed and am poking 
around until I find it, not necessarily finding the best way to get it.

David Lang

**Comment by janmejay** [comment]
Does the crash still happen with error-file enabled?

**Comment by stephanbuys** [comment]
@janmejay, @rgerhards very interesting, that seems to solve it, config now looks like: https://raw.githubusercontent.com/panoptix-za/docker-rsyslog/elasticsearch/json.conf

    ...
               bulkmode="on"
               errorFile="/var/log/rsyslog/ES-error.log"
               erroronly="on"
               interleaved="on"
    ...

This is running on `Ubuntu 14.04.2` (and yes there are errors coming through to `/var/log/rsyslog/ES-error.log`), `rsyslog` installed form the `v8-stable` PPA.

    rsyslogd 8.9.0, compiled with:
    	PLATFORM:				x86_64-pc-linux-gnu
    	PLATFORM (lsb_release -d):		
    	FEATURE_REGEXP:				Yes
    	GSSAPI Kerberos 5 support:		No
    	FEATURE_DEBUG (debug build, slow code):	No
    	32bit Atomic operations supported:	Yes
    	64bit Atomic operations supported:	Yes
    	memory allocator:			system default
    	Runtime Instrumentation (slow code):	No
    	uuid support:				Yes
    	Number of Bits in RainerScript integers: 64

**Comment by joschi99** [comment]
I tried to insert in the rsyslog.conf the 3 lines regarding the errorfile and it seems that this resolves the problem. My working config actually is:

    *.* action(type="omelasticsearch"
           server="localhost"
           serverport="9200"
           template="RSyslog"
           searchType="RSyslog-Osiris"
           searchIndex="logstash-index"
           dynSearchIndex="on"
           bulkmode="on"
           errorFile="/var/log/rsyslogES-error.log"
           erroronly="on"
           interleaved="on"
           queue.type="linkedlist"
           queue.size="10000"
           queue.dequeuebatchsize="5000"
           queue.saveonshutdown="on"
           queue.workerthreads="5"
           action.resumeretrycount="-1"
    )
I checked the error-file rsyslogES-error.log and there is 1 entry:

    {
        "url":  "http://localhost:9200/_bulk?",
        "response":     [{
                        "request":      "{\"index\":{\"_index\": \"rsyslog-2015.04.15\",\"_type\":\"RSyslog-Osiris\"}}\n{\"@timestamp\":\"2015-04-15T10:17:53.057456+02:00\",\"timegenerated\":\"2015-04-15T10:17:53.057456+02:00\",\"message\":\"ACPI: PCI Interrupt Routing Table [\\_SB_.PCI0._PRT]\",\"host\":\"osiris2\",\"fromhost\":\"osiris2\",\"fromhost-ip\":\"127.0.0.1\",\"input-type\":\"imklog\",\"priority\":\"debug\",\"priority-id\":\"7\",\"severity\":\"debug\",\"severity-id\":\"7\",\"facility\":\"kern\",\"facility-id\":\"0\",\"programname\":\"kernel\",\"syslogtag\":\"kernel:\"}\n",
                        "reply":        "{\"_index\":\"rsyslog-2015.04.15\",\"_type\":\"RSyslog-Osiris\",\"_id\":\"AUy8KFh-bcrkBkQy4ucW\",\"status\":400,\"error\":\"MapperParsingException[failed to parse [message]]; nested: JsonParseException[Unrecognized character escape '_' (code 95)\\n at [Source: [B@2135dc50; line: 1, column: 149]]; \"}"
                }]
    }

This is running on SL6.6 with EL 1.5.1 and Rsyslog 8.9.0-1.el6

**Comment by janmejay** [comment]
This https://github.com/rsyslog/rsyslog/pull/303 should fix it.

**Comment by joschi99** [comment]
I updated the RSyslog 8.9.0 with the new rpms version 8.9.0.ad1-1.el6, but the error is still there. It works only when the errorfile setting is present. Is the fix in the rpm-package?

**Comment by janmejay** [comment]
The patch set containing fix for this is not released yet. It'll likely be
released in 8.10.

You can cherrypick commits from PR on to 8.9.0 if you need this fixed
immediately.

--
Regards,
Janmejay

PS: Please blame the typos in this mail on my phone's uncivilized soft
keyboard sporting it's not-so-smart-assist technology.

**Comment by rgerhards** [comment]
This is merged now, to be released with 8.10.0.
