### ISSUE TITLE
omfile leaks file descriptor when using dynafile

### ISSUE THREAD

**Issue by Jean-Daniel** [rsyslog/rsyslog#3909]
I'm using a rsyslog server to centralize logs from many servers, and want to make the log rotate automatically.

So I'm using dynafile and set the date in the file name like this:

```
template(name="file.lts" type="list") {
  constant(value="/srv/rsyslog/lts/")
  property(name="timereported" dateFormat="year")
  constant(value="-")
  property(name="timereported" dateFormat="month")
  constant(value="-")
  property(name="timereported" dateFormat="day")
  constant(value="/")
  property(name="hostname")
  constant(value="/")
  property(name="$.logpath")
  constant(value=".log")
}

ruleset(name="LTS") {
   set $.logpath = "logfile.log"
    action(name="write.lts" type="omfile" dynaFile="file.lts" dynaFileCacheSize="512" Template="LogFormat"
           flushOnTXEnd="off" asyncWriting="on" flushInterval="1" ioBufferSize="256k"
           FileCreateMode="0640" DirCreateMode="0750")
}
```

### Expected behavior

I expect that the count of opened files remains low.

### Actual behavior

The count of opened files always increases, and rsyslog keep very old logs opened. It also have many descriptors opened on the same output file.

When I list the opened file descriptors: I can see something like this:

```
l-wx------ 1 syslog syslog 64 Oct 16 15:36 12 -> /srv/rsyslog/lts/2019-10-16/prx3/nginx/https.log
l-wx------ 1 syslog syslog 64 Oct 16 15:36 13 -> /srv/rsyslog/lts/2019-10-16/prx3/proxy.log
l-wx------ 1 syslog syslog 64 Oct 16 15:36 14 -> /srv/rsyslog/lts/2019-10-16/prx3/nginx/https.log
l-wx------ 1 syslog syslog 64 Oct 16 15:36 15 -> /srv/rsyslog/lts/2019-10-16/prx3/nginx/https_error.log
l-wx------ 1 syslog syslog 64 Oct 16 15:36 16 -> /srv/rsyslog/lts/2019-10-16/prx3/proxy.log
l-wx------ 1 syslog syslog 64 Oct 16 15:36 17 -> /srv/rsyslog/lts/2019-10-16/prx3/nginx/https.log
l-wx------ 1 syslog syslog 64 Oct 16 15:36 18 -> /srv/rsyslog/lts/2019-10-16/prx3/nginx/https_error.log
l-wx------ 1 syslog syslog 64 Oct 16 15:36 19 -> /srv/rsyslog/lts/2019-10-16/prx3/nginx/https.log
l-wx------ 1 syslog syslog 64 Oct 16 15:36 2 -> /dev/null
l-wx------ 1 syslog syslog 64 Oct 16 15:36 20 -> /srv/rsyslog/lts/2019-10-16/prx3/nginx/https_error.log
l-wx------ 1 syslog syslog 64 Oct 16 15:36 21 -> /srv/rsyslog/lts/2019-10-17/prx3/nginx/https.log
l-wx------ 1 syslog syslog 64 Oct 16 15:36 22 -> /srv/rsyslog/lts/2019-10-17/prx3/nginx/https.log
l-wx------ 1 syslog syslog 64 Oct 16 15:36 23 -> /srv/rsyslog/lts/2019-10-17/prx3/nginx/https_error.log
l-wx------ 1 syslog syslog 64 Oct 16 15:36 24 -> /srv/rsyslog/lts/2019-10-17/prx3/nginx/https.log
l-wx------ 1 syslog syslog 64 Oct 16 15:36 25 -> /srv/rsyslog/lts/2019-10-17/prx3/proxy.log
l-wx------ 1 syslog syslog 64 Oct 16 15:36 26 -> /srv/rsyslog/lts/2019-10-17/prx3/nginx/https_error.log
l-wx------ 1 syslog syslog 64 Oct 16 15:36 27 -> /srv/rsyslog/lts/2019-10-17/prx3/nginx/https.log
l-wx------ 1 syslog syslog 64 Oct 16 15:36 28 -> /srv/rsyslog/lts/2019-10-17/prx3/nginx/https_error.log
l-wx------ 1 syslog syslog 64 Oct 17 11:38 29 -> /srv/rsyslog/lts/2019-10-17/prx3/nginx/https_error.log
lr-x------ 1 syslog syslog 64 Oct 16 15:36 3 -> /dev/urandom
l-wx------ 1 syslog syslog 64 Oct 16 15:36 30 -> /srv/rsyslog/lts/2019-10-17/prx3/proxy.log
l-wx------ 1 syslog syslog 64 Oct 17 12:38 31 -> /srv/rsyslog/lts/2019-10-17/prx3/nginx/https.log
l-wx------ 1 syslog syslog 64 Oct 17 14:38 32 -> /srv/rsyslog/lts/2019-10-17/prx3/nginx/https_error.log
l-wx------ 1 syslog syslog 64 Oct 16 15:36 33 -> /srv/rsyslog/lts/2019-10-17/prx3/proxy.log
lrwx------ 1 syslog syslog 64 Oct 16 15:36 4 -> 'socket:[1004844565]'
```

Sending a SIGHUP does not improve the situation. All old file descriptors remain opened and usually it leaks a couple of new one.

### Steps to reproduce the behavior

Running a simple rsyslog server that ingest logs from a imrelp and push them into a single ruleset with a single omfile module.

### Environment
```
rsyslogd  8.1910.0 (aka 2019.10) compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):                Ubuntu 18.04.3 LTS		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Config file:				/etc/rsyslog.conf
	PID file:				/var/run/rsyslogd.pid
	Number of Bits in RainerScript integers: 64
```

**Comment by rgerhards** [comment]
> Running a simple rsyslog server that ingest logs from a imrelp and push them into a single ruleset with a single omfile module.

It's unfortunately not that simple to reproduce. Do you have any additional information? Please note that there is a potentially related issue tracker: https://github.com/rsyslog/rsyslog/issues/3885

**Comment by rgerhards** [comment]
@Jean-Daniel can you turn off async writing, at least for testing? Did this problem only occur after an update (aka "are older versions affected")?

Side-note: async writing, when not using compression or similar cpu intensive tasks, usually slows things down. Writing to plain files is very fast and async writing just adds overhead.

**Comment by Jean-Daniel** [comment]
> > Running a simple rsyslog server that ingest logs from a imrelp and push them into a single ruleset with a single omfile module.
> 
> It's unfortunately not that simple to reproduce.

I guess this is a very hard bug to track as while my instance consistently leaks file descriptors, the rate of leaked fd is random, but look correlated to the server load. This is probably due to a race condition (which would mean that #3885 may also affect amd64).

> Side-note: async writing, when not using compression or similar cpu intensive tasks, usually slows things down.

I misunderstood the `async` parameter.
After rereading the doc, I think in my use case `flushOnTXEnd="off"` is what I was looking for. I disabled `async` on one of my server, and will let you know if that solves the issue. I have to let it run at least one full day to make sure it works.

**Comment by Jean-Daniel** [comment]
Looks like disabling `async` solve my issue.

**Comment by rgerhards** [comment]
> Looks like disabling `async` solve my issue.

thx! This helps nail down the triggering condition.

**Comment by rgerhards** [comment]
fixed by https://github.com/rsyslog/rsyslog/pull/3922

**Comment by Ehekatl** [comment]
still reproducible on rsyslogd  8.1911.0.9edc8875b8f2
send SIGHUP does not release fd

![Screen Shot 2019-12-12 at 7 57 41 PM](https://user-images.githubusercontent.com/7362589/70710215-b073fa00-1d19-11ea-9964-fd7cc4d51c4b.png)
