### ISSUE TITLE
OpenSSL Version to old, SSL_CONF_cmd API  is not supported. [v8.1908.0 try https://www.rsyslog.com/e/2095 ] & netstream session 0x7f5034045c50 from 10.#.#.# will be closed due to error [v8.1908.0 try https://www.rsyslog.com/e/2089 on Amazon Linux AMI  VERSION="2018.03"

### ISSUE THREAD

**Issue by mike1li** [rsyslog/rsyslog#3945]
### Expected behavior
Error free for an rsyslog env with ossl plugin running behind AWS NetworkLoadBalancer running Health checks on tcp10514
rsyslog-8.1908.0-2.el6.x86_64
rsyslog-gnutls-8.1908.0-2.el6.x86_64
rsyslog-openssl-8.1908.0-2.el6.x86_64

### Actual behavior
Seeing 2 errors after setting the Rsyslog debug on using steps from https://www.rsyslog.com/how-to-use-debug-on-demand/

### Steps to reproduce the behavior
Seeing 2 errors after setting the Rsyslog debug on using steps from https://www.rsyslog.com/how-to-use-debug-on-demand/
[root@ip-10-162-66-69 app_splunk_dev_19-3]# export RSYSLOG_DEBUG="DebugOnDemand NoStdOut"
[root@ip-10-162-66-69 app_splunk_dev_19-3]# export RSYSLOG_DEBUGLOG=/var/log/all/rsyslogdebug.log
[root@ip-10-162-66-69 app_splunk_dev_19-3]# /etc/rc.d/init.d/rsyslog stop
Shutting down system logger:                               [  OK  ]
[root@ip-10-162-66-69 app_splunk_dev_19-3]# rsyslogd -n
/var/log/all/rsyslogdebug.log attached
[rsyslogdebug-114.log](https://github.com/rsyslog/rsyslog/files/3804370/rsyslogdebug-114.log)

### Environment
- rsyslog version: 
rsyslog-8.1908.0-2.el6.x86_64
rsyslog-gnutls-8.1908.0-2.el6.x86_64
rsyslog-openssl-8.1908.0-2.el6.x86_64
- platform: 
cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

- for configuration questions/issues, include rsyslog.conf and included config files
#3757 module(load="imuxsock") # provides support for local system logging (e.g. via logger command)
module(load="imklog")   # provides kernel logging support (previously done by rklogd)

module(load="imudp" SchedulingPolicy="fifo" SchedulingPriority="5" threads="2" timeRequery="8" batchSize="128")
input(type="imudp" port="514")

module(load="imptcp") # needs to be done just once
input(type="imptcp" port="514")

$MaxOpenFiles 102400

$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

$template snippedFileFormat, "%$year% %timegenerated% %HOSTNAME% %msg%\n"
$template snippedXDPFileFormat, "%msg%\n"
$template PanFileFormat, "%HOSTNAME%\,%msg%\r\n"
$template VormetricFF, "%$year% %timegenerated% %HOSTNAME% %syslogtag% %structured-data%\n"

$IncludeConfig /etc/rsyslog.d/*.conf
$IncludeConfig /etc/rsyslog.d/snipped/*.conf

global(
defaultNetstreamDriverCAFile="/opt/snipped/etc/apps/proofpoint/certs/cis-eng-ca.pem"
defaultNetstreamDriverCertFile="/opt/snipped/etc/apps/proofpoint/certs/logforwarder.snipped.pem"
defaultNetstreamDriverKeyFile="/opt/snipped/etc/apps/proofpoint/certs/logforwarder.snipped.pem"
)
module(
load="imtcp"
StreamDriver.Name="ossl"
StreamDriver.mode="1"
StreamDriver.AuthMode="anon"
)
input(type="imtcp" port="10514")

if $programname == 'puppet-agent' then                   -/var/log/all/puppet
if $programname == 'puppet-master' then                  -/var/log/all/puppet
if $programname == 'puppet-user' then                    -/var/log/all/puppet

*.info;mail.none;authpriv.none;cron.none                /var/log/messages

authpriv.*                                              /var/log/secure

mail.*                                                  /var/log/maillog

cron.*                                                  /var/log/cron

*.emerg                                                 :omusrmsg:*
uucp,news.crit                                          /var/log/spooler
local7.*                                                /var/log/boot.log

auth.debug      -/var/log/all/auth.log
authpriv.debug  -/var/log/all/authpriv.log
cron.debug      -/var/log/all/cron.log
daemon.debug    -/var/log/all/daemon.log
ftp.debug       -/var/log/all/ftp.log
kern.debug      -/var/log/all/kern.log
lpr.debug       -/var/log/all/lpr.log
mail.debug      -/var/log/all/mail.log
news.debug      -/var/log/all/news.log
syslog.debug    -/var/log/all/syslog.log
user.debug      -/var/log/all/user.log
uucp.debug      -/var/log/all/uucp.log
local0.debug    -/var/log/all/local0.log
local1.debug    -/var/log/all/local1.log
local2.debug    -/var/log/all/local2.log
local3.debug    -/var/log/all/local3.log
local4.debug    -/var/log/all/local4.log
local5.debug    -/var/log/all/local5.log
local6.debug    -/var/log/all/local6.log
local7.debug    -/var/log/all/local7.log

if $programname == 'snipped-drupal' then /var/log/drupal/drupal.log

template (name="Trend" type="string" string="/var/log/trend/trend_ds.log")
if ( $source == 'localhost' or $fromhost-ip == '127.0.0.1' ) and $syslogfacility-text == 'local5' then
{
action(type="omfile" dynaFile="Trend" template="RSYSLOG_TraditionalFileFormat")
stop
}

**Comment by alorbach** [comment]
This is proberly related to this issue here: 
https://github.com/rsyslog/rsyslog/pull/3944

There was a wrong version check causing OpenSSL 1.0.2 to be considered as too old. 
Its corrected in this PR

**Comment by mike1li** [comment]
Thanks @alorbach . Upgraded to rsyslog1910.  
rsyslog-gnutls-8.1910.0-1.el6.x86_64
rsyslog-openssl-8.1910.0-1.el6.x86_64
rsyslog-8.1910.0-1.el6.x86_64

Still getting:
rsyslogd: netstream session 0x7fac2c211b60 from 10.#.#.# will be closed due to error [v8.1910.0 try https://www.rsyslog.com/e/2089 ] Debug file is +10MB. What should I filter out & attach?

**Comment by alorbach** [comment]
@mike1li : You will have to compile from source and merge this PR #3944 or wait until the PR is being merged.

**Comment by davidelang** [comment]
does this error actually prevent the setting from working? or is this just a 
cosmetic error.

David Lang

**Comment by mike1li** [comment]
@alorbach Thanks. 
@davidelang even if the setting is working, it is not ideal to keep on seeing the following noises in the log:
2019 Nov  5 11:11:42 ip-10-#-#-#  netstream session 0x7f16424bf0a0 from 10.162.64.61 will be closed due to error [v8.1910.0 try https://www.rsyslog.com/e/2089 ]
2019 Nov  5 11:11:42 ip-10-#-#-#  SSL_ERROR_SSL in 'osslEndSess' [v8.1910.0]
2019 Nov  5 11:11:42 ip-10-#-#-#  OpenSSL Error Stack: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init [v8.1910.0]
2019 Nov  5 11:11:42 ip-10-#-#-#  SSL_ERROR_SYSCALL in 'osslHandshakeCheck Server' [v8.1910.0]
2019 Nov  5 11:11:42 ip-10-#-#-#  SSL_ERROR_SYSCALL in 'osslHandshakeCheck Server' [v8.1910.0]

**Comment by mike1li** [comment]
@davidelang besides the "netstream session will be closed due to error", there are a lot of 

2019 Nov  8 13:10:27 ip-10.#.#.#  SSL_ERROR_SSL in 'osslEndSess' [v8.1910.0]
2019 Nov  8 13:10:27 ip-10.#.#.#  OpenSSL Error Stack: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init [v8.1910.0]
....
2019 Nov  8 13:20:34 ip-10.#.#.#  SSL_ERROR_SSL in 'osslEndSess' [v8.1910.0]
2019 Nov  8 13:20:34 ip-10.#.#.#  OpenSSL Error Stack: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init [v8.1910.0]
2019 Nov  8 13:20:46 ip-10.#.#.#  SSL_ERROR_SSL in 'osslEndSess' [v8.1910.0]
2019 Nov  8 13:20:46 ip-10.#.#.#  OpenSSL Error Stack: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init [v8.1910.0]
2019 Nov  8 13:20:56 ip-10.#.#.#  SSL_ERROR_SSL in 'osslEndSess' [v8.1910.0]
2019 Nov  8 13:20:56 ip-10.#.#.#  OpenSSL Error Stack: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init [v8.1910.0]
I counted ~50 of such set of messages within a span of 10 minutes.

**Comment by alorbach** [comment]
This looks like not ssl enabled clients trying to connect syslog server.

**Comment by mike1li** [comment]
@alanrobson in respect to what SSL_ERROR_SSL messages? Is there a way to log the source ip ? Thanks

**Comment by mike1li** [comment]
@alorbach  Upgraded to v8.1911.0. Seeing the source ips causing the "netstream session will be closed due to error [v8.1911.0 try https://www.rsyslog.com/e/2089 ]"
Also saw a new error: rsyslogd: Uncompression of a message failed with return code -3 - enable debug logging if you need further information. Message ignored. [v8.1911.0]
[rsyslogdebug-2019111310AMEST.log.zip](https://github.com/rsyslog/rsyslog/files/3842087/rsyslogdebug-2019111310AMEST.log.zip). Also uploaded rsyslogdebug-2019111310AMEST.log.zip. Please advise on the options for resolution. Thanks.

**Comment by rgerhards** [comment]
@mike1li unfortunately the linked-to debug log is unreadable

**Comment by mike1li** [comment]
@rgerhards sorry it is tgz file.

**Comment by rgerhards** [comment]
@mike1li you should post all error messages - the debug log has ample of them. If you give only the last one, you make your life more miserable that it needs to be ;-)

That said, I see
```
error:00000005:lib(0):func(0):DH lib(5)
```
searching for this error brings up:

https://stackoverflow.com/questions/47023626/openssl-ssl-read-failure-error00000005lib0func0dh-lib

Looking at the first anwers the reason seems to be a connection closure.

@alorbach could you please have a look at the first answer as well. I guess we could improve error reporting.

**Comment by alorbach** [comment]
@rgerhards I saw the guithub issue related to this: https://github.com/openssl/openssl/issues/1903

I think using BIO_eof might be useful to detection connection closures, I will look into this and see how we can test this.

**Comment by rgerhards** [comment]
@alorbach regarding testing, it's a bit tricky. I would guess that running tcpflood in the background and `kill -9` it could do the trick.

**Comment by alorbach** [comment]
regarding the issue in the debug log on top (https://github.com/rsyslog/rsyslog/files/3804370/rsyslogdebug-114.log) it won't change anything as the error is happening on Handshake. 

However for SSL_Read / SSL_Write it could enhance the session shutdown handling. 

At first I will make sure the eror is printed out properly.

**Comment by alorbach** [comment]
Regarding error ouput, this will be fixed with https://github.com/rsyslog/rsyslog/pull/3968 and looks like this now: 

> rsyslogd: SSL_ERROR_SSL Error in 'osslRecordRecv': 'error:00000001:lib(0):func(0):reason(1)(1)' with ret=-1  [v8.2001.0.master]
> rsyslogd: OpenSSL Error Stack: error:1417C086:SSL routines:tls_process_client_certificate:certificate verify failed [v8.2001.0.master]
>

**Comment by ionosphere80** [comment]
@mike1li Network load balancer health checks simply open TCP connections to target group ports. If the connection succeeds, the NLB closes the connection and considers the service healthy. Unfortunately, SSL libraries (OpenSSL and GnuTLS) interpret the health check as a connection failure because it lacks TLS negotiation. NLBs perform health checks at a rather high rate, especially if you're using multiple AZs, so you'll see plenty of errors in the logs. I used a filter to remove them from the log processing flow.

**Comment by alorbach** [comment]
I need to research why we used 4 and now 2 but as far as I can see, there is no deeper reason why thge SSL_set_verify_depth and depth was reduced from 4 to 2, most likely because it was taken from openssl sample code. 

We can change this default back to 4 and make it configurable.

**Comment by mike1li** [comment]
> 
> 
> @mike1li Network load balancer health checks simply open TCP connections to target group ports. If the connection succeeds, the NLB closes the connection and considers the service healthy. Unfortunately, SSL libraries (OpenSSL and GnuTLS) interpret the health check as a connection failure because it lacks TLS negotiation. NLBs perform health checks at a rather high rate, especially if you're using multiple AZs, so you'll see plenty of errors in the logs. I used a filter to remove them from the log processing flow.

@ionosphere80  Yes there are constant/high rate AWS NLB health checks on tcp_10514. I think there should be some logic to handle load balancer health check which may lack tls/ssl negotiation. Thanks.

**Comment by rgerhards** [comment]
Apologies for the very late follow-up. This may no longer be relevant for the original reporter, but I am adding the answer for people who arrive here through search while we work through the backlog. We do not like to close issues just because of age; this is an old platform/library support case.

The `SSL_CONF_cmd API is not supported` warning comes from an OpenSSL/library build that is too old for the TLS configuration-command feature being requested. Current documentation expects OpenSSL support for that API when using those TLS config commands.

The AWS Network Load Balancer TCP health check is also relevant: a plain TCP health check against a TLS syslog port can create connection-close/noise messages because it is not a TLS syslog client.

Closing this as answered/old platform support. If this still happens on a supported current rsyslog package and OpenSSL version, please open a new issue with the current package versions, TLS config commands, and the exact health-check behavior.
