### ISSUE TITLE
mmanon: IPv6 addresses followed by a port (in not recommended from) are not rewritten properly 

### ISSUE THREAD

**Issue by xshadow** [rsyslog/rsyslog#4725]
Dear rsyslog team, thanks for your nice software. I found a bug in mmanons IPv6 log anonymization. The IPv6 log anonymization is not recognizing IPv6 addresses properly when the IPv6 address is followed by a port. 

If a 4 digit port is append to the IPv6 address, the first 4 digits are not rewritten, instead the port gets obfuscated.

```
1a00:c820:1180:c84c:ad3f:4024:d991:ec2e:4922 becomes 1a00:0:0:0:0:0:0:0:0
``` 

If a 5 digit port is append to the IPv6 address, the complete IPv6 address is written to the logfile.

```
1a00:c820:1180:c84c:ad3f:4024:d991:ec2e:49225 stays 1a00:c820:1180:c84c:ad3f:4024:d991:ec2e:49225
```

### Expected behavior

I would expect that the IPv6 address is properly removed from the syslog file.

### Actual behavior

An IPv6 address followed by a five digit port is not recognized as IPv6 address and the log filter is not applied.
Example log message: 

```
Nov  1 16:35:44 webserver apache: [Mon Nov 01 16:35:44.705418 2021] [authz_core:error] [pid 3195941:tid 139935243814656] [client ca00:6920:e180:c12c:ed3f:3024:d991:ec2e:64833] AH01630: client denied by server configuration: /var/www/www.mysite.to/www/xmlrpc.php`
```

### Steps to reproduce the behavior

```
ansible@host:~# logger "Catched IPv6 without port 1a00:c820:1180:c84c:ad3f:4024:d991:ec2e"
ansible@host:~# logger "Catched IPv6 with 4digit port 1a00:c820:1180:c84c:ad3f:4024:d991:ec2e:4922"
ansible@host:~# logger "Uncatched IPv6 with 5digit port 1a00:c820:1180:c84c:ad3f:4024:d991:ec2e:49225"

# File: /var/log/syslog

Nov  1 16:52:01 host ansible: Catched IPv6 without port 0:0:0:0:0:0:0:0
Nov  1 16:52:13 host ansible: Catched IPv6 with 4digit port 1a00:0:0:0:0:0:0:0:0
Nov  1 16:52:27 host ansible: Uncatched IPv6 with 5digit port 1a00:c820:1180:c84c:ad3f:4024:d991:ec2e:49225
```

### Environment
```
rsyslogd  8.2102.0 (aka 2021.02) compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Config file:				/etc/rsyslog.conf
	PID file:				/run/rsyslogd.pid
	Number of Bits in RainerScript integers: 64

See https://www.rsyslog.com for more information.
```

```
#File:  /etc/rsyslog.d/20-anon.conf 
module(load="mmanon")
action(type="mmanon" mode="zero" ipv4.bits="32" ipv6.bits="128")
```

**Comment by rgerhards** [comment]
I see where the problem stems from. Apache seems to use a representation which is not recommended by the relevant RFC and we did most probably not take this form into account when crafting the anonymizer.

Relevant RFC part here: https://datatracker.ietf.org/doc/html/rfc5952#section-6

As this is in the wild and Apache is quite common, it looks like we need to add support for this form of port representation.

**Comment by xshadow** [comment]
Thank you very much! 

I tried to understand what you mean with recommended representation. When looking into the RFC I read that the a representation form is `2001:db8::1:80` isn't that exactly what Apache is doing ?

**Comment by rgerhards** [comment]
do not read just the bullet points, but also the normative text ;-) 

After the bullet point, it says "The situation is not much different in IPv4, but the most ambiguous case with IPv6 is the second bullet.  This is due to the "::"usage inIPv6 addresses. This style is NOT RECOMMENDED because of its ambiguity.  The [] style as expressed in [RFC3986] SHOULD be employed, and is the default unless otherwise specified."

**Comment by xshadow** [comment]
Thanks.

**Comment by geor-g** [comment]
This was fixed in Debian unstable via `rsyslog/8.2110.0-4`; a Debian stable fix is underway and a preliminary package `rsyslog/8.2102.0-2+deb11u1` has been [published](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000335#59). In case people running Debian are reading this, I believe it makes sense if those people could test this package and report their findings to the linked bug report.

**Comment by doobry-systemli** [comment]
Unfortunately, the fix isn't sufficient. Shortened IPv6 addresses that lack (hex)diggits between two colons are still not anonymized.

**Comment by doobry-systemli** [comment]
A reproducer for a case that isn't caught yet would be the following:

```
logger "Uncatched IPv6 with 5digit port 1a00:c820:1180:c84c:ad3f::d991:ec2e:49225"
```
